# Generated by Django 4.0 on 2024-01-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_rename_urls_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='uuid',
            new_name='unid',
        ),
    ]
